# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-05 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paterno', models.CharField(max_length=10)),
                ('materno', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=20)),
            ],
        ),
    ]
